title: Md Motakabbir Rahman
description: An Electrical Engineer with expertise in open-source DC grid design, photovoltaic energy, and power electronics. <br/>  London, ON, Canada <br/> Email- motakabbir71@gmail.com <br/> LinkedIn- motakabbir71
theme: jekyll-theme-dinky
