title: Md Motakabbir Rahman
logo: /files/img/DSC08310.jpg
description: An Electrical Engineer with expertise in open-source DC grid design, photovoltaic energy, and power electronics. Seeking to contribute to solar PV designs. <br/> Location- London, Ontario, Canada <br/> Email- motakabbir71@gmail.com <br/> LinkedIn- https://www.linkedin.com/in/motakabbir71/
theme: jekyll-theme-hacker
