title: Md Motakabbir Rahman
#logo: https://github.com/motakabbirrahman/motakabbirrahman.github.io/blob/75ea26aedd6a34085b1e2c130f031c9f1a70f8f7/Asstes/DSC08310.jpg
#description: An Electrical Engineer with expertise in open-source DC grid design, photovoltaic energy, and power electronics. Seeking to contribute to solar PV designs.
theme: jekyll-theme-minimal
